# -*- coding: utf-8 -*-
"""A7_v2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K2Qoegp9PPLpPvVPYY5Vw7F0xgQwtqw0
"""

import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
from torch.utils.data import TensorDataset, DataLoader
import torchvision.models 
from torchvision.models import resnet50, ResNet50_Weights
import copy
#!pip install paramparse

from PIL import Image
device = torch.device("mps")
print(device)

train_set  = np.load("D:\cmput 328/a7/train_X.npy")
train_labels_set = np.load("D:\cmput 328/a7/train_Y.npy")

valid_set  = np.load("D:\cmput 328/a7/valid_X.npy")
valid_labels_set = np.load("D:\cmput 328/a7/valid_Y.npy")


train_bboxes_set = np.load("D:\cmput 328/a7/train_bboxes.npy")
valid_bboxes_set = np.load("D:\cmput 328/a7/valid_bboxes.npy")


# git clone https://github.com/ultralytics/yolov5
# pip install -r yolov5/requirements.txt

model = torch.hub.load('ultralytics/yolov5', 'yolov5s')

# python3 yolov5/train.py --img 320 --batch 32 --epochs 50 --data dataset.yaml --weights yolov5s.pt --workers 1

"""This is for deployment

"""

#model = torch.hub.load('ultralytics/yolov5', 'custom', path='yolov5/runs/train/exp15/weights/last.pt', force_reload=True)

# Commented out IPython magic to ensure Python compatibility.
src_img = train_set[300, ...].squeeze().reshape((64, 64, 3)).astype(np.uint8)

results = model(src_img)
results.print()

# %matplotlib inline 
# plt.imshow(np.squeeze(results.render()))
# plt.show()

